### ISSUE TITLE
Do not paginate through all pages by default

### ISSUE THREAD

**Issue by julienr** [Picterra/picterra-python#111]
We have a helper function `_paginate_through_list` that's used in a few of the `list_XXX` functions like `list_rasters`, `list_detectors`.  This will end up paginating through all the pages by default.

This feels like a historical default that doesn't make much sense anymore. On an account with 10k rasters, the call could take a long time.

It feels we should expose pagination more explicitely and have the caller go through all pages themselves if they really want to.

That probably means breaking some API, but we can start by just deprecating those functions and replacing them with new ones.

WDYT @ao-picterra ?

**Comment by ao-picterra** [comment]
100% agree: can't we just bump the library version to 2 and change the list_XXX signature to have page number / size in it?

**Comment by julienr** [comment]
Yeah to make migration somewhat nice, I feel we can:
- publish a 1.X with those new parameters to the `list_XXX` functions
  - They'd still default to listing everything if these params aren't passed, but show a deprecation warning
- publish a v2 with those parameters made mandatory

So you can nicely migrate on 1.x and then switch to v2 when ready.

**Comment by julienr** [comment]
Contradicting my previous comment, supporting both in 1.X seems it won't be possible in the same function - we don't want to force the user to pass a `page_size` for example.

So we'd either have to:
1. introduce entirely new functions with non-conflicting names (`list_rasters` => `rasters_list` or `find_rasters`). I'm unable to come up with good name that are following the pattern of the lib (`<verb>_<entity>`)
2. break the API in v2 without deprecation warnings for v1

I'm gonna go with 2. This is what semantic versionning is for after all.

**Comment by julienr** [comment]
We can still push a 1.X update that shows deprecation warnings for these methods prompting users to update to v2 and explaining the change.
