### ISSUE TITLE
Add full workflow example in /examples

### ISSUE THREAD

**Issue by ao-picterra** [Picterra/picterra-python#19]
- Create a detector
- Upload a raster
- List rasters
- Add raster to detector
- Add annotations to raster
- Train detector
- Set detection area on raster
- Predict on raster
- Download results

**Comment by julienr** [comment]
Seems like we could turn `set_annotations.py` into this.

For the last 3 steps (detecting), I think we can just point to the upload_and_detect example.

**Comment by julienr** [comment]
We have all of this in the docs. Closing this
