### ISSUE TITLE
Handle throttling

### ISSUE THREAD

**Issue by restaste** [Picterra/picterra-python#25]
Currently, a user can get throttled in the middle of a call in the lib (e.g. within a `upload_raster`, let's say after a successful upload the `commit/` gets throttled). This can end up in data being in an un-commited state.

Let's discuss if/how we want to handle throttling in the lib. One option is to pass a `max_retries` kwarg in all functions, and retry with an exponential backoff on HTTP 429.

**Comment by ao-picterra** [comment]
I'd say in this one we could also implement a backoff wait in case of network errors, though this is a more tricky because for operations that consume MP we'd like to leverage the idempotency key API mechanism (blocked until we have caching on app).

**Comment by ao-picterra** [comment]
@restaste I've started some work on backoff/timeout [here](https://github.com/Picterra/picterra-python/tree/32-backoff-for-network-errors): dunno if can come handy for this too

**Comment by julienr** [comment]
I feel #52 has fixed this one as well. So closing this
